# Generated by Django 4.0.2 on 2022-03-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
