# Generated by Django 4.0.2 on 2022-03-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.URLField(default='test'),
            preserve_default=False,
        ),
    ]
